-- =============================================
-- STUDENT RESULT & ATTENDANCE SYSTEM
-- Oracle Database Schema
-- =============================================

-- 1. Users table (Admin / Teacher / Student login)
CREATE TABLE SR_USERS (
    USERID      NUMBER,
    USERNAME    VARCHAR2(100) NOT NULL,
    USEREMAIL   VARCHAR2(100) NOT NULL,
    USERPASSWORD VARCHAR2(100) NOT NULL,
    USERROLE    VARCHAR2(20)  NOT NULL,   -- 'Admin', 'Teacher', 'Student'
    CONSTRAINT PK_SR_USERS PRIMARY KEY (USERID)
);

-- 2. Classes / Divisions
CREATE TABLE SR_CLASSES (
    CLASSID     NUMBER,
    CLASSNAME   VARCHAR2(50) NOT NULL,    -- e.g. '10th A', '9th B'
    SECTION     VARCHAR2(10),
    CONSTRAINT PK_SR_CLASSES PRIMARY KEY (CLASSID)
);

-- 3. Subjects
CREATE TABLE SR_SUBJECTS (
    SUBJECTID   NUMBER,
    SUBJECTNAME VARCHAR2(100) NOT NULL,   -- e.g. 'Mathematics', 'Science'
    CLASSID     NUMBER,
    CONSTRAINT PK_SR_SUBJECTS PRIMARY KEY (SUBJECTID),
    CONSTRAINT FK_SUBJECT_CLASS FOREIGN KEY (CLASSID) REFERENCES SR_CLASSES(CLASSID)
);

-- 4. Students
CREATE TABLE SR_STUDENTS (
    STUDENTID   NUMBER,
    STUDENTNAME VARCHAR2(100) NOT NULL,
    ROLLNO      VARCHAR2(20)  NOT NULL,
    CLASSID     NUMBER,
    GENDER      VARCHAR2(10),
    PARENTNAME  VARCHAR2(100),
    CONTACTNO   VARCHAR2(20),
    USERID      NUMBER,                   -- linked login account
    CONSTRAINT PK_SR_STUDENTS PRIMARY KEY (STUDENTID),
    CONSTRAINT FK_STUDENT_CLASS FOREIGN KEY (CLASSID) REFERENCES SR_CLASSES(CLASSID),
    CONSTRAINT FK_STUDENT_USER  FOREIGN KEY (USERID)  REFERENCES SR_USERS(USERID)
);

-- 5. Marks / Results
CREATE TABLE SR_MARKS (
    MARKID      NUMBER,
    STUDENTID   NUMBER,
    SUBJECTID   NUMBER,
    EXAMTYPE    VARCHAR2(30),             -- 'Unit Test', 'Mid Term', 'Final'
    MARKSSCORED NUMBER(5,2),
    TOTALMARKS  NUMBER(5,2),
    EXAMDATE    DATE,
    CONSTRAINT PK_SR_MARKS PRIMARY KEY (MARKID),
    CONSTRAINT FK_MARKS_STUDENT FOREIGN KEY (STUDENTID) REFERENCES SR_STUDENTS(STUDENTID),
    CONSTRAINT FK_MARKS_SUBJECT FOREIGN KEY (SUBJECTID) REFERENCES SR_SUBJECTS(SUBJECTID)
);

-- 6. Attendance
CREATE TABLE SR_ATTENDANCE (
    ATTENDANCEID NUMBER,
    STUDENTID    NUMBER,
    CLASSID      NUMBER,
    ATTENDDATE   DATE,
    STATUS       VARCHAR2(10),            -- 'Present', 'Absent', 'Leave'
    CONSTRAINT PK_SR_ATTENDANCE PRIMARY KEY (ATTENDANCEID),
    CONSTRAINT FK_ATTEND_STUDENT FOREIGN KEY (STUDENTID) REFERENCES SR_STUDENTS(STUDENTID),
    CONSTRAINT FK_ATTEND_CLASS   FOREIGN KEY (CLASSID)   REFERENCES SR_CLASSES(CLASSID)
);

-- =============================================
-- SAMPLE DATA
-- =============================================

INSERT INTO SR_USERS VALUES (1, 'Admin',       'admin@school.com',   'admin123',   'Admin');
INSERT INTO SR_USERS VALUES (2, 'Mr. Sharma',  'sharma@school.com',  'teacher123', 'Teacher');
INSERT INTO SR_USERS VALUES (3, 'Ravi Kumar',  'ravi@student.com',   'ravi123',    'Student');
INSERT INTO SR_USERS VALUES (4, 'Priya Singh', 'priya@student.com',  'priya123',   'Student');

INSERT INTO SR_CLASSES VALUES (1, '10th', 'A');
INSERT INTO SR_CLASSES VALUES (2, '10th', 'B');
INSERT INTO SR_CLASSES VALUES (3, '9th',  'A');

INSERT INTO SR_SUBJECTS VALUES (1, 'Mathematics', 1);
INSERT INTO SR_SUBJECTS VALUES (2, 'Science',     1);
INSERT INTO SR_SUBJECTS VALUES (3, 'English',     1);
INSERT INTO SR_SUBJECTS VALUES (4, 'Mathematics', 3);

INSERT INTO SR_STUDENTS VALUES (1, 'Ravi Kumar',  'R001', 1, 'Male',   'Suresh Kumar',  '9876543210', 3);
INSERT INTO SR_STUDENTS VALUES (2, 'Priya Singh', 'R002', 1, 'Female', 'Ramesh Singh',  '9876543211', 4);

INSERT INTO SR_MARKS VALUES (1, 1, 1, 'Mid Term', 78, 100, TO_DATE('2024-10-10','YYYY-MM-DD'));
INSERT INTO SR_MARKS VALUES (2, 1, 2, 'Mid Term', 85, 100, TO_DATE('2024-10-11','YYYY-MM-DD'));
INSERT INTO SR_MARKS VALUES (3, 1, 3, 'Mid Term', 70, 100, TO_DATE('2024-10-12','YYYY-MM-DD'));
INSERT INTO SR_MARKS VALUES (4, 2, 1, 'Mid Term', 90, 100, TO_DATE('2024-10-10','YYYY-MM-DD'));
INSERT INTO SR_MARKS VALUES (5, 2, 2, 'Mid Term', 88, 100, TO_DATE('2024-10-11','YYYY-MM-DD'));

INSERT INTO SR_ATTENDANCE VALUES (1, 1, 1, TO_DATE('2024-11-01','YYYY-MM-DD'), 'Present');
INSERT INTO SR_ATTENDANCE VALUES (2, 1, 1, TO_DATE('2024-11-02','YYYY-MM-DD'), 'Absent');
INSERT INTO SR_ATTENDANCE VALUES (3, 2, 1, TO_DATE('2024-11-01','YYYY-MM-DD'), 'Present');
INSERT INTO SR_ATTENDANCE VALUES (4, 2, 1, TO_DATE('2024-11-02','YYYY-MM-DD'), 'Present');

COMMIT;
